/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import javax.swing.JOptionPane;
import Util.ConectaBanco;
import java.awt.Frame;
import java.awt.Image;

 *
 * @author KOCH
 * @date 10/12/2019
 */
public class Login extends javax.swing.JFrame {
    
    ConectaBanco conecta = new ConectaBanco();
    
     private Login.DaemonThread myThread = null;
     
    //javaCV
    VideoCapture webSource = null;
    
    //openCV
    FaceRecognizer recognizer = LBPHFaceRecognizer.create();

     Mat cameraImage = new Mat();
     
    BytePointer mem = new BytePointer();
    RectVector detectedFaces = new RectVector();
   
    //info
    int id,type;
    String login, senha;
    
    //vars mexer tela
    int xx;
    int xy;
    
    
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        getRootPane().setDefaultButton(jButton1);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txt_user = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Security System - Login");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_user.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txt_user.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(txt_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 280, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Senha");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Usuário");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, -1, -1));

        txt_pass.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txt_pass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(txt_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 280, 30));

        jButton1.setBackground(new java.awt.Color(78, 78, 78));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Entrar");
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setOpaque(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, 150, 40));

        jPanel1.setBackground(new java.awt.Color(151, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8customer100px.png"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 320, 90));

        

        btn_minimizar.setBackground(new java.awt.Color(54, 33, 89));
        
        });
        jPanel4.add(btn_minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, -1, 28));

        
        jPanel4.add(btn_fechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, -1, 28));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 370, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 470));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         login = txt_user.getText();
         senha = txt_pass.getText();
   
         
         
        id = VerificarUser();
        
        
       
        }else if(id != 0){
            startCamera(); 
        }else{
            txt_user.setText("");
            txt_pass.setText("");
            JOptionPane.showMessageDialog(null, "***TENTE NOVAMENTE***");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_minimizarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_minimizarMousePressed
        // TODO add your handling code here:
        setState(Frame.ICONIFIED); // comando que minimiza a tela
    }//GEN-LAST:event_btn_minimizarMousePressed

    private void btn_fecharMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_fecharMousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_fecharMousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form EventQueue.invokeLater */
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_fechar;
    private javax.swing.JLabel btn_minimizar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JTextField txt_user;
    // End of variables declaration//GEN-END:variables

 class DaemonThread implements Runnable {

        protected volatile boolean runnable = false;

        @Override
        public void run() {
            synchronized (this) {
                while (runnable) {
                    try {
                        if (webSource.grab()) {
                            
                            webSource.retrieve(cameraImage);

                            
                                        stopCamera(); 
                                        dispose();
                                    }
                                
                                }
                            }

                            imencode(".bmp", cameraImage, mem);
                            Image im = ImageIO.read(new ByteArrayInputStream(mem.getStringBytes()));
                            

                            
                                if (runnable == false) {
                                    System.out.println("Salve a Foto");
                                    this.wait();    
                            }
                        }
                    } catch (IOException | InterruptedException ex) {
                        System.out.println("Error class DaemonThread da classe Recognizer: " + ex);
                    }
                }
            }
        }

    }
    
 
    
    private int VerificarUser() {
        int idteste=0;
            conecta.conexao();
            try {
                conecta.executaSQL("SELECT id FROM user WHERE username='"+login+"' and password='"+senha+"';");
                conecta.rs.first();
                idteste = conecta.rs.getInt("id");
                type=1;


            } catch (SQLException e) {
                System.out.println("Error no método Verificar, classe RegisterPerson: "+ e);
            }
        return idteste;
    }
    private int VerificarPerson(){
         int idteste=0;
            conecta.conexao();
            try {
                conecta.executaSQL("SELECT id FROM person WHERE first_name='"+login+"' and password='"+senha+"';");
                conecta.rs.first();
                idteste = conecta.rs.getInt("id");
                type=2;

            } catch (SQLException e) {
                System.out.println("Error no método Verificar, classe RegisterPerson: "+ e);
            }
            return idteste;
            }

    private void stopCamera(){
         myThread.runnable = false;
        webSource.release();
    }

    private void startCamera(){
         webSource = new VideoCapture(0);
            myThread = new Login.DaemonThread();
            Thread t = new Thread(myThread);
            t.setDaemon(true);
            myThread.runnable = true;
            t.start();
    }
}
