/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Crud;

import Principal.Home;
import Util.ConectaBanco;
import javax.swing.JOptionPane;


/**
 *
 * @author KOCH
 */
public class UpdateUser extends javax.swing.JFrame {

    // Vars User
    String user, password;
    int idUser=0;
    
    //Utils
    ConectaBanco conecta = new ConectaBanco();
    
    //Vars restaurar Home
    Home home;
    
    //tipo de tela
    //int tipo;
    
    /**
     * Creates new form Update
     */
    public UpdateUser() {
        initComponents();
    }
    
    public UpdateUser(Home home, int tipo){
        initComponents();
        showTableData();
        this.home = home;
        habilitaMenu(tipo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_usuario = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        lbl_senha = new javax.swing.JLabel();
        txt_password = new javax.swing.JTextField();
        
        jPanel4.add(btn_minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, -1, 28));

        btn_fechar.setBackground(new java.awt.Color(54, 33, 89));
        btn_fechar.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        btn_fechar.setForeground(new java.awt.Color(255, 255, 255));
        btn_fechar.setText("X");
        btn_fechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_fecharMousePressed(evt);
            }
        });

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        // TODO add your handling code here:
        
        ControlUser cod = new ControlUser();
        ModelUser mod = new ModelUser();
        
        mod.setId(Integer.parseInt(txt_id.getText()));
        mod.setPassword(txt_password.getText());

        
        dispose(); //fecho o frame atual (Register)
        home.setState(Frame.NORMAL); //restauro o jframe 'home'
        
    }//GEN-LAST:event_btn_editarActionPerformed

    private void btn_deletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deletarActionPerformed
        // TODO add your handling code here:
        ControlUser cod = new ControlUser();       
        dispose(); //fecho o frame atual (Register)
        home.setState(Frame.NORMAL); //restauro o jframe 'home'
    }//GEN-LAST:event_btn_deletarActionPerformed

    private void btn_minimizarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_minimizarMousePressed
        // TODO add your handling code here:
        setState(Frame.ICONIFIED); // comando que minimiza a tela

    }//GEN-LAST:event_btn_minimizarMousePressed

    private void btn_fecharMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_fecharMousePressed
        // TODO add your handling code here:

        dispose(); //fecho o frame atual (Register)
        home.setState(Frame.NORMAL); //restauro o jframe 'home'
    }//GEN-LAST:event_btn_fecharMousePressed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_deletar;
    private javax.swing.JButton btn_editar;
    private javax.swing.JLabel btn_fechar;
    private javax.swing.JLabel btn_minimizar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_senha;
    private javax.swing.JLabel lbl_usuario;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_password;
    private javax.swing.JLabel txt_title_menu;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables

    private void habilitaMenu(int tipo){
        if(tipo == 1){ // abre menu tipo deletar
            //tornando nao editaveis
            txt_username.setEditable(false);
            txt_password.setEditable(false);
            //mudando a cor da fonte do label

            
        }else if(tipo == 2){ // abre menu tipo editar
            //tornando nao editavel e mudando as cores de fundo e da fonte
            btn_deletar.setEnabled(false);
            btn_deletar.setBackground(new Color(150,150,150));
        }
    }

    private void showTableData(){
        try {
            ControlUser cod = new ControlUser();

            cod.selecionar(mod,jTable1);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"erro showTableData() classe UpdateUser: "+ e);
        }
    }

}
